// SPDX-License-Identifier: Apache-2.0
plugins {
    id("org.hiero.gradle.module.library")
    id("org.hiero.gradle.feature.antlr")
    id("org.hiero.gradle.feature.protobuf") // protobuf is only used for tests
    id("org.hiero.gradle.feature.benchmark")
}

description =
    "A high performance Google Protocol Buffers parser, code generator, and runtime library."

testModuleInfo {
    requires("com.google.protobuf")
    requires("org.assertj.core")
    requires("net.bytebuddy")
    requires("org.junit.jupiter.api")
    requires("org.junit.jupiter.params")
    requires("org.mockito")
    requires("org.mockito.junit.jupiter")
}

// Define package name for code generated by ANTLR
tasks.generateGrammarSource {
    arguments = arguments + listOf("-package", "com.hedera.pbj.runtime.jsonparser")
}
