/*
 * Copyright (C) 2022-2025 Hedera Hashgraph, LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

plugins {
    id("org.hiero.gradle.module.library")
    id("org.hiero.gradle.feature.antlr")
    id("org.hiero.gradle.feature.protobuf") // protobuf is only used for tests
    id("org.hiero.gradle.feature.benchmark")
}

description =
    "A high performance Google Protocol Buffers parser, code generator, and runtime library."

testModuleInfo {
    requires("com.google.protobuf")
    requires("org.assertj.core")
    requires("net.bytebuddy")
    requires("org.junit.jupiter.api")
    requires("org.junit.jupiter.params")
    requires("org.mockito")
    requires("org.mockito.junit.jupiter")
    requiresStatic("com.github.spotbugs.annotations")
}

// Define package name for code generated by ANTLR
tasks.generateGrammarSource {
    arguments = arguments + listOf("-package", "com.hedera.pbj.runtime.jsonparser")
}
