# SPDX-License-Identifier: Apache-2.0
# Logging setup, useful for debugging.

# ALL FINEST FINER FINE CONFIG INFO WARNING SEVERE OFF
.level=INFO

# Helidon loggers
io.helidon.level=INFO
io.helidon.webserver.level=INFO
#io.helidon.http.http2.level=FINEST

# Use FINE to see metadata about frames, and FINER to see the bytes:
io.helidon.http.http2.Http2LoggingFrameListener.level=INFO

#io.helidon.config.level=SEVERE
#io.helidon.security.level=INFO
#io.helidon.common.level=INFO
# Override the chatty HTTP server internals
com.sun.net.httpserver.level = WARNING
com.sun.net.httpserver.ServerImpl.level = WARNING
com.sun.net.httpserver.ExchangeImpl.level = WARNING

# Configure handlers
handlers = java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.level = ALL
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter
java.util.logging.SimpleFormatter.format = %TF %<TT.%<TL%<Tz %4$-7s [%2$s] %5$s%6$s%n
