name: "ZXF: Build Application [On: Commit]"
on:
  push:
    branches:
      - main
      - release/*
    tags:
      - v*

defaults:
  run:
    shell: bash

concurrency:
  group: build-pbj-library-${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: Code
    uses: ./.github/workflows/zxc-compile-pbj-code.yaml
    with:
      enable-unit-tests: true
      enable-integration-tests: true
      enable-jmh-tests: true
    secrets:
      access-token: ${{ secrets.GH_ACCESS_TOKEN }}
      codacy-project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
